name: gokv CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Deno fmt check
        run: deno fmt --check

      - name: Deno lint
        run: deno lint

  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Testing
        env:
          GOKV_WS_LOG: true
          GOKV_ENV: development
          GOKV_TOKEN: ${{ secrets.GOKV_TOKEN }}
        run: deno test -A

  test2:
    name: Testing (Node.js)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [14, 16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Testing
        env:
          GOKV_WS_LOG: true
          GOKV_ENV: development
          GOKV_TOKEN: ${{ secrets.GOKV_TOKEN }}
        run: pnpm test
