name: gokv CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Code Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Deno fmt check
        run: deno fmt --check

      - name: Deno lint
        run: deno lint

  test:
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Deno test
        env:
          GOKV_TOKEN: ${{ secrets.GOKV_TOKEN }}
        run: deno test -A src/ test/deno_test.ts
