name: gokv CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Deno fmt check
        run: deno fmt --check

      - name: Deno lint
        run: deno lint

  test:
    name: Testing in Deno
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.18

      - name: Installation pnpm
        run: npm install -g pnpm

      - name: Testing in Deno
        env:
          GOKV_TOKEN: ${{ secrets.GOKV_TOKEN }}
        run: deno test -A src/ test/

      - name: Build dist
        run: pnpm install && pnpm build:all

      - name: Testing in Node.js
        env:
          GOKV_TOKEN: ${{ secrets.GOKV_TOKEN }}
        run: node test/integration-test-node.mjs
